version: '3'

services:
    linux-gui:
        env_file:
            - ./src/.env
        build:
            context: ./src
            dockerfile: ./Dockerfile
        volumes:
            - ./data/:/root/Desktop/
        ports:
            - "5900:5900"
            - "6080:80"
